//! C ABI bindings for the `tpt-fem` core (cdylib + staticlib, dev-only this pass).
//!
//! Mirrors the Python bindings (`tpt-fem-py`): a mesh handle plus
//! `tpt_solve_poisson` / `tpt_solve_elasticity` / `tpt_solve_modal` /
//! `tpt_topopt_cantilever`. The header `include/tpt_fem.h` is generated by
//! cbindgen from this file.
//!
//! # Conventions
//!
//! * Objects are opaque heap handles returned through `out` pointers; each has
//!   a matching `tpt_*_free` (which accepts NULL).
//! * Fallible functions return an `int32_t` status: [`TPT_OK`] (0) on success,
//!   otherwise one of the `TPT_ERR_*` codes. A human-readable message for the
//!   most recent failure on the calling thread is available from
//!   [`tpt_last_error_message`].
//! * No panic ever crosses the FFI boundary (it becomes [`TPT_ERR_PANIC`]).
//! * Arrays are passed as `(pointer, length)`. Read-only data pointers returned
//!   by accessors stay valid until the owning handle is freed.

use std::cell::RefCell;
use std::ffi::{c_char, c_void, CStr, CString};
use std::panic::{catch_unwind, AssertUnwindSafe};

use ::tpt_fem::{
    box_mesh as rs_box_mesh, cantilever_load, solve_elasticity as rs_solve_elasticity,
    solve_modal as rs_solve_modal, solve_poisson as rs_solve_poisson, topopt_simp,
    write_vtk_with_data, CellType, ElasticModel, Grid, Mesh as RsMesh, PointData, TopOptParams,
};

/// Success.
pub const TPT_OK: i32 = 0;
/// A pointer argument was NULL, a string was not UTF-8, or a value was out of range.
pub const TPT_ERR_INVALID_ARG: i32 = 1;
/// The solver / mesh library reported an error.
pub const TPT_ERR_SOLVE: i32 = 2;
/// A file could not be read or written.
pub const TPT_ERR_IO: i32 = 3;
/// A Rust panic was caught at the FFI boundary.
pub const TPT_ERR_PANIC: i32 = 4;

// ---------------------------------------------------------------------------
// Error plumbing
// ---------------------------------------------------------------------------

struct FfiError {
    code: i32,
    msg: String,
}

type FfiResult<T> = Result<T, FfiError>;

fn err<T>(code: i32, msg: impl Into<String>) -> FfiResult<T> {
    Err(FfiError {
        code,
        msg: msg.into(),
    })
}

thread_local! {
    static LAST_ERROR: RefCell<CString> = RefCell::new(CString::default());
}

fn set_last_error(msg: &str) {
    // Interior NULs cannot occur in a CString; replace them rather than lose the message.
    let c = CString::new(msg.replace('\0', " ")).unwrap_or_default();
    LAST_ERROR.with(|e| *e.borrow_mut() = c);
}

/// Run `f`, converting `Err` and panics into a status code + last-error message.
fn guard<F: FnOnce() -> FfiResult<()>>(f: F) -> i32 {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(Ok(())) => TPT_OK,
        Ok(Err(e)) => {
            set_last_error(&e.msg);
            e.code
        }
        Err(p) => {
            let detail = p
                .downcast_ref::<&str>()
                .map(|s| s.to_string())
                .or_else(|| p.downcast_ref::<String>().cloned())
                .unwrap_or_else(|| "unknown panic".into());
            set_last_error(&format!("panic: {detail}"));
            TPT_ERR_PANIC
        }
    }
}

/// Message describing the most recent failure on the calling thread
/// (empty string if none). Valid until the next failing call on this thread;
/// do not free it.
#[no_mangle]
pub extern "C" fn tpt_last_error_message() -> *const c_char {
    LAST_ERROR.with(|e| e.borrow().as_ptr())
}

/// Library version, e.g. `"0.1.0"`. Static; do not free.
#[no_mangle]
pub extern "C" fn tpt_version() -> *const c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0").as_ptr() as *const c_char
}

// ---------------------------------------------------------------------------
// Pointer helpers
// ---------------------------------------------------------------------------

unsafe fn slice<'a, T>(p: *const T, len: usize, what: &str) -> FfiResult<&'a [T]> {
    if len == 0 {
        return Ok(&[]);
    }
    if p.is_null() {
        return err(TPT_ERR_INVALID_ARG, format!("{what} is NULL"));
    }
    Ok(std::slice::from_raw_parts(p, len))
}

unsafe fn cstr<'a>(p: *const c_char, what: &str) -> FfiResult<&'a str> {
    if p.is_null() {
        return err(TPT_ERR_INVALID_ARG, format!("{what} is NULL"));
    }
    CStr::from_ptr(p)
        .to_str()
        .or_else(|_| err(TPT_ERR_INVALID_ARG, format!("{what} is not valid UTF-8")))
}

unsafe fn r#ref<'a, T>(p: *const T, what: &str) -> FfiResult<&'a T> {
    match p.as_ref() {
        Some(r) => Ok(r),
        None => err(TPT_ERR_INVALID_ARG, format!("{what} is NULL")),
    }
}

unsafe fn put<T>(out: *mut *mut T, v: T) -> FfiResult<()> {
    if out.is_null() {
        return err(TPT_ERR_INVALID_ARG, "out pointer is NULL");
    }
    *out = Box::into_raw(Box::new(v));
    Ok(())
}

unsafe fn free<T>(p: *mut T) {
    if !p.is_null() {
        drop(Box::from_raw(p));
    }
}

fn solve_err<T, E: std::fmt::Display>(r: Result<T, E>) -> FfiResult<T> {
    r.or_else(|e| err(TPT_ERR_SOLVE, e.to_string()))
}

// Model parsing / dimension mirror `tpt-fem-py` (`parse_model`, `dim_of`).
fn dim_of(mesh: &RsMesh) -> FfiResult<usize> {
    match mesh.elements.first().map(|e| e.cell_type) {
        Some(CellType::Line) => Ok(1),
        Some(
            CellType::Tri | CellType::Quad | CellType::Tri6 | CellType::Quad8 | CellType::Quad9,
        ) => Ok(2),
        Some(
            CellType::Tet | CellType::Hex | CellType::Tet10 | CellType::Hex20 | CellType::Hex27,
        ) => Ok(3),
        None => err(TPT_ERR_INVALID_ARG, "mesh has no elements"),
    }
}

fn parse_model(s: &str) -> FfiResult<ElasticModel> {
    match s.to_ascii_lowercase().replace(['-', '_'], "").as_str() {
        "bar" | "baraxial" => Ok(ElasticModel::BarAxial),
        "planestress" => Ok(ElasticModel::PlaneStress),
        "planestrain" => Ok(ElasticModel::PlaneStrain),
        "3d" | "continuum" | "continuum3d" => Ok(ElasticModel::Continuum3D),
        other => err(
            TPT_ERR_INVALID_ARG,
            format!("unknown elasticity model '{other}' (bar | plane-stress | plane-strain | 3d)"),
        ),
    }
}

// ---------------------------------------------------------------------------
// Boundary-condition records
// ---------------------------------------------------------------------------

/// Scalar Dirichlet condition `u[node] = value` (Poisson).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TptNodeBc {
    pub node: usize,
    pub value: f64,
}

/// Vector Dirichlet condition on one component of a node (elasticity / modal);
/// the global DOF is `node * dim + component`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TptDofBc {
    pub node: usize,
    pub component: usize,
    pub value: f64,
}

fn dof_bcs(bcs: &[TptDofBc], dim: usize) -> FfiResult<Vec<(usize, f64)>> {
    bcs.iter()
        .map(|b| {
            if b.component >= dim {
                err(
                    TPT_ERR_INVALID_ARG,
                    format!("bc component {} out of range for dim {dim}", b.component),
                )
            } else {
                Ok((b.node * dim + b.component, b.value))
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Mesh
// ---------------------------------------------------------------------------

/// Opaque mesh handle.
pub struct TptMesh {
    inner: RsMesh,
}

/// Load a Gmsh `.msh` (v4.1) file.
///
/// # Safety
/// `path` must be a valid NUL-terminated string; `out` a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_load(path: *const c_char, out: *mut *mut TptMesh) -> i32 {
    guard(|| {
        let path = cstr(path, "path")?;
        let bytes = std::fs::read(path)
            .or_else(|e| err(TPT_ERR_IO, format!("read {path}: {e}")))?;
        let inner = solve_err(RsMesh::from_msh_bytes(&bytes))?;
        put(out, TptMesh { inner })
    })
}

/// Build a structured tetrahedral box mesh of `[min, max]` with `n[i]` cells per axis.
///
/// # Safety
/// `min`, `max` (3 doubles) and `n` (3 `size_t`) must be valid; `out` a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_box(
    min: *const f64,
    max: *const f64,
    n: *const usize,
    out: *mut *mut TptMesh,
) -> i32 {
    guard(|| {
        let min = slice(min, 3, "min")?;
        let max = slice(max, 3, "max")?;
        let n = slice(n, 3, "n")?;
        if n.contains(&0) {
            return err(TPT_ERR_INVALID_ARG, "n must be >= 1 on every axis");
        }
        let inner = rs_box_mesh(
            [min[0], min[1], min[2]],
            [max[0], max[1], max[2]],
            [n[0], n[1], n[2]],
        );
        put(out, TptMesh { inner })
    })
}

/// Free a mesh (NULL is a no-op).
///
/// # Safety
/// `mesh` must come from this library and not be used afterwards.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_free(mesh: *mut TptMesh) {
    free(mesh)
}

/// Number of nodes (0 if `mesh` is NULL).
///
/// # Safety
/// `mesh` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_node_count(mesh: *const TptMesh) -> usize {
    mesh.as_ref().map_or(0, |m| m.inner.node_count())
}

/// Copy the coordinates of node `i` into `out[0..3]` (unused trailing entries are 0).
///
/// # Safety
/// `mesh` must be a valid handle and `out` point to 3 writable doubles.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_coords(mesh: *const TptMesh, i: usize, out: *mut f64) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        if out.is_null() {
            return err(TPT_ERR_INVALID_ARG, "out is NULL");
        }
        if i >= m.inner.node_count() {
            return err(TPT_ERR_INVALID_ARG, format!("node {i} out of range"));
        }
        let c = m.inner.node_coords(i);
        for k in 0..3 {
            *out.add(k) = c.get(k).copied().unwrap_or(0.0);
        }
        Ok(())
    })
}

/// snprintf-style copy of a node list: writes up to `cap` ids to `buf` and
/// always stores the total match count in `*count`.
unsafe fn copy_ids(ids: &[usize], buf: *mut usize, cap: usize, count: *mut usize) -> FfiResult<()> {
    if count.is_null() {
        return err(TPT_ERR_INVALID_ARG, "count is NULL");
    }
    *count = ids.len();
    if cap > 0 {
        if buf.is_null() {
            return err(TPT_ERR_INVALID_ARG, "buf is NULL");
        }
        for (k, id) in ids.iter().take(cap).enumerate() {
            *buf.add(k) = *id;
        }
    }
    Ok(())
}

/// Node ids whose `axis` coordinate is within `tol` of `coord`.
/// Writes up to `cap` ids into `buf` and the total count into `*count`
/// (call once with `cap = 0` to size the buffer).
///
/// # Safety
/// `mesh` valid; `buf` points to `cap` writable `size_t`s (may be NULL if `cap == 0`); `count` valid.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_nodes_on_plane(
    mesh: *const TptMesh,
    axis: usize,
    coord: f64,
    tol: f64,
    buf: *mut usize,
    cap: usize,
    count: *mut usize,
) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        if axis > 2 {
            return err(TPT_ERR_INVALID_ARG, "axis must be 0, 1 or 2");
        }
        copy_ids(&m.inner.nodes_on_plane(axis, coord, tol), buf, cap, count)
    })
}

/// Node ids inside the axis-aligned box `[min, max]`; buffer semantics as
/// [`tpt_mesh_nodes_on_plane`].
///
/// # Safety
/// `mesh` valid; `min`/`max` point to 3 doubles; `buf`/`count` as above.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_nodes_in_box(
    mesh: *const TptMesh,
    min: *const f64,
    max: *const f64,
    buf: *mut usize,
    cap: usize,
    count: *mut usize,
) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        let min = slice(min, 3, "min")?;
        let max = slice(max, 3, "max")?;
        let ids = m
            .inner
            .nodes_in_box([min[0], min[1], min[2]], [max[0], max[1], max[2]]);
        copy_ids(&ids, buf, cap, count)
    })
}

/// Write the mesh and an optional per-node scalar field (`values`, one per
/// node; pass NULL / 0 for none) to a ParaView `.vtk` file.
///
/// # Safety
/// `mesh` valid; `path`, `field_name` valid C strings; `values` points to `len` doubles.
#[no_mangle]
pub unsafe extern "C" fn tpt_mesh_write_vtk(
    mesh: *const TptMesh,
    path: *const c_char,
    field_name: *const c_char,
    values: *const f64,
    len: usize,
) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        let path = cstr(path, "path")?;
        let data = if values.is_null() || len == 0 {
            vec![]
        } else {
            let name = cstr(field_name, "field_name")?;
            vec![PointData::new(name, slice(values, len, "values")?.to_vec())]
        };
        write_vtk_with_data(&m.inner, &data, path)
            .or_else(|e| err(TPT_ERR_IO, e.to_string()))
    })
}

// ---------------------------------------------------------------------------
// Field (Poisson / elasticity result)
// ---------------------------------------------------------------------------

/// Opaque per-node solution field. Scalar fields have `dim == 1`; elasticity
/// fields hold `dim` interleaved components per node.
pub struct TptField {
    values: Vec<f64>,
    dim: usize,
}

/// Number of doubles in the field (`node_count * dim`); 0 if NULL.
///
/// # Safety
/// `f` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_field_len(f: *const TptField) -> usize {
    f.as_ref().map_or(0, |f| f.values.len())
}

/// Components per node (1 for Poisson); 0 if NULL.
///
/// # Safety
/// `f` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_field_dim(f: *const TptField) -> usize {
    f.as_ref().map_or(0, |f| f.dim)
}

/// Read-only pointer to the field values; valid until `tpt_field_free`. NULL if `f` is NULL.
///
/// # Safety
/// `f` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_field_data(f: *const TptField) -> *const f64 {
    f.as_ref().map_or(std::ptr::null(), |f| f.values.as_ptr())
}

/// Free a field (NULL is a no-op).
///
/// # Safety
/// `f` must come from this library and not be used afterwards.
#[no_mangle]
pub unsafe extern "C" fn tpt_field_free(f: *mut TptField) {
    free(f)
}

/// Callback returning the Poisson source `f(x, y, z)`; `user` is passed through.
pub type TptSourceFn = Option<extern "C" fn(x: f64, y: f64, z: f64, user: *mut c_void) -> f64>;

/// Solve `-∇·(k ∇u) = f` on `mesh`.
///
/// The source is `source_fn(x, y, z, user)` if `source_fn` is non-NULL,
/// otherwise the constant `source_const`. The callback runs on the calling thread.
///
/// # Safety
/// `mesh` valid; `bcs` points to `n_bcs` records; `out` valid; `source_fn` (if any) must be safe to call with `user`.
#[no_mangle]
pub unsafe extern "C" fn tpt_solve_poisson(
    mesh: *const TptMesh,
    conductivity: f64,
    quad_order: usize,
    source_const: f64,
    source_fn: TptSourceFn,
    user: *mut c_void,
    bcs: *const TptNodeBc,
    n_bcs: usize,
    out: *mut *mut TptField,
) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        let bcs: Vec<(usize, f64)> = slice(bcs, n_bcs, "bcs")?
            .iter()
            .map(|b| (b.node, b.value))
            .collect();
        let f = move |x: &[f64]| -> f64 {
            match source_fn {
                Some(cb) => cb(
                    x.first().copied().unwrap_or(0.0),
                    x.get(1).copied().unwrap_or(0.0),
                    x.get(2).copied().unwrap_or(0.0),
                    user,
                ),
                None => source_const,
            }
        };
        let values = solve_err(rs_solve_poisson(
            &m.inner,
            conductivity,
            quad_order,
            f,
            &bcs,
            None,
            None,
        ))?;
        put(out, TptField { values, dim: 1 })
    })
}

/// Solve linear-elasticity statics on `mesh`. `model` is `"bar"`,
/// `"plane-stress"`, `"plane-strain"` or `"3d"`.
///
/// # Safety
/// `mesh` valid; `model` a valid C string; `bcs` points to `n_bcs` records; `out` valid.
#[no_mangle]
pub unsafe extern "C" fn tpt_solve_elasticity(
    mesh: *const TptMesh,
    model: *const c_char,
    young: f64,
    poisson: f64,
    quad_order: usize,
    bcs: *const TptDofBc,
    n_bcs: usize,
    out: *mut *mut TptField,
) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        let model = parse_model(cstr(model, "model")?)?;
        let dim = dim_of(&m.inner)?;
        let dir = dof_bcs(slice(bcs, n_bcs, "bcs")?, dim)?;
        let values = solve_err(rs_solve_elasticity(
            &m.inner,
            model,
            young,
            poisson,
            quad_order,
            |_| vec![0.0; dim],
            &dir,
        ))?;
        put(out, TptField { values, dim })
    })
}

// ---------------------------------------------------------------------------
// Modal
// ---------------------------------------------------------------------------

/// Opaque set of natural-vibration modes (`K φ = ω² M φ`).
pub struct TptModal {
    dim: usize,
    omega2s: Vec<f64>,
    shapes: Vec<Vec<f64>>,
}

/// Solve the natural-vibration eigenproblem on `mesh`, extracting `num_modes` modes.
///
/// # Safety
/// `mesh` valid; `model` a valid C string; `bcs` points to `n_bcs` records; `out` valid.
#[no_mangle]
pub unsafe extern "C" fn tpt_solve_modal(
    mesh: *const TptMesh,
    model: *const c_char,
    young: f64,
    poisson: f64,
    density: f64,
    quad_order: usize,
    num_modes: usize,
    bcs: *const TptDofBc,
    n_bcs: usize,
    out: *mut *mut TptModal,
) -> i32 {
    guard(|| {
        let m = r#ref(mesh, "mesh")?;
        let model = parse_model(cstr(model, "model")?)?;
        let dim = dim_of(&m.inner)?;
        let dir = dof_bcs(slice(bcs, n_bcs, "bcs")?, dim)?;
        let modes = solve_err(rs_solve_modal(
            &m.inner, model, young, poisson, density, quad_order, num_modes, &dir,
        ))?;
        let (omega2s, shapes): (Vec<f64>, Vec<Vec<f64>>) = modes.into_iter().unzip();
        put(
            out,
            TptModal {
                dim,
                omega2s,
                shapes,
            },
        )
    })
}

/// Number of modes found; 0 if NULL.
///
/// # Safety
/// `m` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_modal_count(m: *const TptModal) -> usize {
    m.as_ref().map_or(0, |m| m.omega2s.len())
}

/// Components per node of the mode shapes; 0 if NULL.
///
/// # Safety
/// `m` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_modal_dim(m: *const TptModal) -> usize {
    m.as_ref().map_or(0, |m| m.dim)
}

/// Squared natural frequency ω² of mode `i` (NaN if out of range).
///
/// # Safety
/// `m` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_modal_omega2(m: *const TptModal, i: usize) -> f64 {
    m.as_ref()
        .and_then(|m| m.omega2s.get(i).copied())
        .unwrap_or(f64::NAN)
}

/// Length of mode `i`'s shape vector (`node_count * dim`); 0 if out of range.
///
/// # Safety
/// `m` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_modal_shape_len(m: *const TptModal, i: usize) -> usize {
    m.as_ref()
        .and_then(|m| m.shapes.get(i))
        .map_or(0, |s| s.len())
}

/// Read-only pointer to mode `i`'s shape; valid until `tpt_modal_free`. NULL if out of range.
///
/// # Safety
/// `m` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_modal_shape(m: *const TptModal, i: usize) -> *const f64 {
    m.as_ref()
        .and_then(|m| m.shapes.get(i))
        .map_or(std::ptr::null(), |s| s.as_ptr())
}

/// Free a modal result (NULL is a no-op).
///
/// # Safety
/// `m` must come from this library and not be used afterwards.
#[no_mangle]
pub unsafe extern "C" fn tpt_modal_free(m: *mut TptModal) {
    free(m)
}

// ---------------------------------------------------------------------------
// Topology optimization
// ---------------------------------------------------------------------------

/// Opaque SIMP topology-optimization result.
pub struct TptTopopt {
    nx: usize,
    ny: usize,
    densities: Vec<f64>,
    compliance: Vec<f64>,
    iterations: usize,
}

/// SIMP minimum-compliance optimization of a 2-D cantilever on an `nx × ny`
/// grid of unit elements (left edge clamped, unit downward load at the
/// bottom-right corner). Typical defaults: `penal = 3`, `filter_radius = 1.5`, `max_iter = 50`.
///
/// # Safety
/// `out` must be a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_cantilever(
    nx: usize,
    ny: usize,
    vol_frac: f64,
    penal: f64,
    filter_radius: f64,
    max_iter: usize,
    out: *mut *mut TptTopopt,
) -> i32 {
    guard(|| {
        if nx < 1 || ny < 1 {
            return err(TPT_ERR_INVALID_ARG, format!("nx and ny must be >= 1, got {nx} x {ny}"));
        }
        if !(vol_frac > 0.0 && vol_frac <= 1.0) {
            return err(TPT_ERR_INVALID_ARG, format!("vol_frac must be in (0, 1], got {vol_frac}"));
        }
        if penal < 1.0 {
            return err(TPT_ERR_INVALID_ARG, format!("penal must be >= 1, got {penal}"));
        }
        if filter_radius < 0.0 {
            return err(
                TPT_ERR_INVALID_ARG,
                format!("filter_radius must be >= 0, got {filter_radius}"),
            );
        }
        let grid = Grid::new(nx + 1, ny + 1, 1.0);
        let (f, bcs) = cantilever_load(&grid, 1.0);
        let params = TopOptParams {
            grid,
            e0: 1.0,
            nu: 0.3,
            vol_frac,
            penal,
            filter_radius,
            max_iter,
            move_limit: 0.2,
        };
        let res = solve_err(topopt_simp(&params, &f, &bcs))?;
        put(
            out,
            TptTopopt {
                nx,
                ny,
                densities: res.densities,
                compliance: res.compliance,
                iterations: res.iterations,
            },
        )
    })
}

/// Elements along `x`; 0 if NULL.
///
/// # Safety
/// `t` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_nx(t: *const TptTopopt) -> usize {
    t.as_ref().map_or(0, |t| t.nx)
}

/// Elements along `y`; 0 if NULL.
///
/// # Safety
/// `t` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_ny(t: *const TptTopopt) -> usize {
    t.as_ref().map_or(0, |t| t.ny)
}

/// Iterations performed; 0 if NULL.
///
/// # Safety
/// `t` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_iterations(t: *const TptTopopt) -> usize {
    t.as_ref().map_or(0, |t| t.iterations)
}

/// Read-only pointer to the `nx * ny` element densities; valid until `tpt_topopt_free`.
///
/// # Safety
/// `t` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_densities(t: *const TptTopopt) -> *const f64 {
    t.as_ref().map_or(std::ptr::null(), |t| t.densities.as_ptr())
}

/// Length of the compliance history; 0 if NULL.
///
/// # Safety
/// `t` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_compliance_len(t: *const TptTopopt) -> usize {
    t.as_ref().map_or(0, |t| t.compliance.len())
}

/// Read-only pointer to the compliance history; valid until `tpt_topopt_free`.
///
/// # Safety
/// `t` must be NULL or a valid handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_compliance(t: *const TptTopopt) -> *const f64 {
    t.as_ref().map_or(std::ptr::null(), |t| t.compliance.as_ptr())
}

/// Free a topology-optimization result (NULL is a no-op).
///
/// # Safety
/// `t` must come from this library and not be used afterwards.
#[no_mangle]
pub unsafe extern "C" fn tpt_topopt_free(t: *mut TptTopopt) {
    free(t)
}
