/* tpt-fem C API. Generated by cbindgen from crates/tpt-fem-capi; do not edit. */

#ifndef TPT_FEM_H
#define TPT_FEM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

// Success.
#define TPT_OK 0

// A pointer argument was NULL, a string was not UTF-8, or a value was out of range.
#define TPT_ERR_INVALID_ARG 1

// The solver / mesh library reported an error.
#define TPT_ERR_SOLVE 2

// A file could not be read or written.
#define TPT_ERR_IO 3

// A Rust panic was caught at the FFI boundary.
#define TPT_ERR_PANIC 4

// Opaque per-node solution field. Scalar fields have `dim == 1`; elasticity
// fields hold `dim` interleaved components per node.
typedef struct TptField TptField;

// Opaque mesh handle.
typedef struct TptMesh TptMesh;

// Opaque set of natural-vibration modes (`K φ = ω² M φ`).
typedef struct TptModal TptModal;

// Opaque SIMP topology-optimization result.
typedef struct TptTopopt TptTopopt;

// Callback returning the Poisson source `f(x, y, z)`; `user` is passed through.
typedef double (*TptSourceFn)(double x, double y, double z, void *user);

// Scalar Dirichlet condition `u[node] = value` (Poisson).
typedef struct TptNodeBc {
  size_t node;
  double value;
} TptNodeBc;

// Vector Dirichlet condition on one component of a node (elasticity / modal);
// the global DOF is `node * dim + component`.
typedef struct TptDofBc {
  size_t node;
  size_t component;
  double value;
} TptDofBc;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Message describing the most recent failure on the calling thread
// (empty string if none). Valid until the next failing call on this thread;
// do not free it.
const char *tpt_last_error_message(void);

// Library version, e.g. `"0.1.0"`. Static; do not free.
const char *tpt_version(void);

// Load a Gmsh `.msh` (v4.1) file.
//
// # Safety
// `path` must be a valid NUL-terminated string; `out` a valid pointer.
int32_t tpt_mesh_load(const char *path, struct TptMesh **out);

// Build a structured tetrahedral box mesh of `[min, max]` with `n[i]` cells per axis.
//
// # Safety
// `min`, `max` (3 doubles) and `n` (3 `size_t`) must be valid; `out` a valid pointer.
int32_t tpt_mesh_box(const double *min, const double *max, const size_t *n, struct TptMesh **out);

// Free a mesh (NULL is a no-op).
//
// # Safety
// `mesh` must come from this library and not be used afterwards.
void tpt_mesh_free(struct TptMesh *mesh);

// Number of nodes (0 if `mesh` is NULL).
//
// # Safety
// `mesh` must be NULL or a valid handle.
size_t tpt_mesh_node_count(const struct TptMesh *mesh);

// Copy the coordinates of node `i` into `out[0..3]` (unused trailing entries are 0).
//
// # Safety
// `mesh` must be a valid handle and `out` point to 3 writable doubles.
int32_t tpt_mesh_coords(const struct TptMesh *mesh, size_t i, double *out);

// Node ids whose `axis` coordinate is within `tol` of `coord`.
// Writes up to `cap` ids into `buf` and the total count into `*count`
// (call once with `cap = 0` to size the buffer).
//
// # Safety
// `mesh` valid; `buf` points to `cap` writable `size_t`s (may be NULL if `cap == 0`); `count` valid.
int32_t tpt_mesh_nodes_on_plane(const struct TptMesh *mesh,
                                size_t axis,
                                double coord,
                                double tol,
                                size_t *buf,
                                size_t cap,
                                size_t *count);

// Node ids inside the axis-aligned box `[min, max]`; buffer semantics as
// [`tpt_mesh_nodes_on_plane`].
//
// # Safety
// `mesh` valid; `min`/`max` point to 3 doubles; `buf`/`count` as above.
int32_t tpt_mesh_nodes_in_box(const struct TptMesh *mesh,
                              const double *min,
                              const double *max,
                              size_t *buf,
                              size_t cap,
                              size_t *count);

// Write the mesh and an optional per-node scalar field (`values`, one per
// node; pass NULL / 0 for none) to a ParaView `.vtk` file.
//
// # Safety
// `mesh` valid; `path`, `field_name` valid C strings; `values` points to `len` doubles.
int32_t tpt_mesh_write_vtk(const struct TptMesh *mesh,
                           const char *path,
                           const char *field_name,
                           const double *values,
                           size_t len);

// Number of doubles in the field (`node_count * dim`); 0 if NULL.
//
// # Safety
// `f` must be NULL or a valid handle.
size_t tpt_field_len(const struct TptField *f);

// Components per node (1 for Poisson); 0 if NULL.
//
// # Safety
// `f` must be NULL or a valid handle.
size_t tpt_field_dim(const struct TptField *f);

// Read-only pointer to the field values; valid until `tpt_field_free`. NULL if `f` is NULL.
//
// # Safety
// `f` must be NULL or a valid handle.
const double *tpt_field_data(const struct TptField *f);

// Free a field (NULL is a no-op).
//
// # Safety
// `f` must come from this library and not be used afterwards.
void tpt_field_free(struct TptField *f);

// Solve `-∇·(k ∇u) = f` on `mesh`.
//
// The source is `source_fn(x, y, z, user)` if `source_fn` is non-NULL,
// otherwise the constant `source_const`. The callback runs on the calling thread.
//
// # Safety
// `mesh` valid; `bcs` points to `n_bcs` records; `out` valid; `source_fn` (if any) must be safe to call with `user`.
int32_t tpt_solve_poisson(const struct TptMesh *mesh,
                          double conductivity,
                          size_t quad_order,
                          double source_const,
                          TptSourceFn source_fn,
                          void *user,
                          const struct TptNodeBc *bcs,
                          size_t n_bcs,
                          struct TptField **out);

// Solve linear-elasticity statics on `mesh`. `model` is `"bar"`,
// `"plane-stress"`, `"plane-strain"` or `"3d"`.
//
// # Safety
// `mesh` valid; `model` a valid C string; `bcs` points to `n_bcs` records; `out` valid.
int32_t tpt_solve_elasticity(const struct TptMesh *mesh,
                             const char *model,
                             double young,
                             double poisson,
                             size_t quad_order,
                             const struct TptDofBc *bcs,
                             size_t n_bcs,
                             struct TptField **out);

// Solve the natural-vibration eigenproblem on `mesh`, extracting `num_modes` modes.
//
// # Safety
// `mesh` valid; `model` a valid C string; `bcs` points to `n_bcs` records; `out` valid.
int32_t tpt_solve_modal(const struct TptMesh *mesh,
                        const char *model,
                        double young,
                        double poisson,
                        double density,
                        size_t quad_order,
                        size_t num_modes,
                        const struct TptDofBc *bcs,
                        size_t n_bcs,
                        struct TptModal **out);

// Number of modes found; 0 if NULL.
//
// # Safety
// `m` must be NULL or a valid handle.
size_t tpt_modal_count(const struct TptModal *m);

// Components per node of the mode shapes; 0 if NULL.
//
// # Safety
// `m` must be NULL or a valid handle.
size_t tpt_modal_dim(const struct TptModal *m);

// Squared natural frequency ω² of mode `i` (NaN if out of range).
//
// # Safety
// `m` must be NULL or a valid handle.
double tpt_modal_omega2(const struct TptModal *m, size_t i);

// Length of mode `i`'s shape vector (`node_count * dim`); 0 if out of range.
//
// # Safety
// `m` must be NULL or a valid handle.
size_t tpt_modal_shape_len(const struct TptModal *m, size_t i);

// Read-only pointer to mode `i`'s shape; valid until `tpt_modal_free`. NULL if out of range.
//
// # Safety
// `m` must be NULL or a valid handle.
const double *tpt_modal_shape(const struct TptModal *m, size_t i);

// Free a modal result (NULL is a no-op).
//
// # Safety
// `m` must come from this library and not be used afterwards.
void tpt_modal_free(struct TptModal *m);

// SIMP minimum-compliance optimization of a 2-D cantilever on an `nx × ny`
// grid of unit elements (left edge clamped, unit downward load at the
// bottom-right corner). Typical defaults: `penal = 3`, `filter_radius = 1.5`, `max_iter = 50`.
//
// # Safety
// `out` must be a valid pointer.
int32_t tpt_topopt_cantilever(size_t nx,
                              size_t ny,
                              double vol_frac,
                              double penal,
                              double filter_radius,
                              size_t max_iter,
                              struct TptTopopt **out);

// Elements along `x`; 0 if NULL.
//
// # Safety
// `t` must be NULL or a valid handle.
size_t tpt_topopt_nx(const struct TptTopopt *t);

// Elements along `y`; 0 if NULL.
//
// # Safety
// `t` must be NULL or a valid handle.
size_t tpt_topopt_ny(const struct TptTopopt *t);

// Iterations performed; 0 if NULL.
//
// # Safety
// `t` must be NULL or a valid handle.
size_t tpt_topopt_iterations(const struct TptTopopt *t);

// Read-only pointer to the `nx * ny` element densities; valid until `tpt_topopt_free`.
//
// # Safety
// `t` must be NULL or a valid handle.
const double *tpt_topopt_densities(const struct TptTopopt *t);

// Length of the compliance history; 0 if NULL.
//
// # Safety
// `t` must be NULL or a valid handle.
size_t tpt_topopt_compliance_len(const struct TptTopopt *t);

// Read-only pointer to the compliance history; valid until `tpt_topopt_free`.
//
// # Safety
// `t` must be NULL or a valid handle.
const double *tpt_topopt_compliance(const struct TptTopopt *t);

// Free a topology-optimization result (NULL is a no-op).
//
// # Safety
// `t` must come from this library and not be used afterwards.
void tpt_topopt_free(struct TptTopopt *t);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TPT_FEM_H */
